# Executive Summary {.unnumbered} {.title-block}

This is the National Inventory Report (NIR) of the United Republic of Tanzania for 2024, submitted to the United Nations Framework Convention on Climate Change (UNFCCC) as part of its reporting obligations. The NIR contains national greenhouse gas emission inventory estimates for the period 1990–2021, compiled under the UNFCCC rules for reporting. This report and the associated tables are submitted to fulfil Tanzania’s obligations under the enhanced national communication reporting requirements (Article 12, paragraph 1(a) of the Convention, and decisions 1/CP.16 para 60(a–b)). The NIR also supports compliance with the reporting requirements in the preparation of Tanzania's first biennial update report (BUR) consistent with decision 1/CP.16 para 60(c). This is the second time Tanzania has prepared its NIR, but the first submission under the "BUR" reporting mechanism. 

The NIR has been prepared in accordance with the UNFCCC guidelines for the preparation of national communications from non-Annex I Parties (decision 17/CP.8) and the UNFCCC biennial update reporting guidelines for Parties not included in Annex I to the Convention (decision 2/CP.17, paragraph 40, and annex III of decision 2/CP.17). The compilation of the NIR followed the 2006 IPCC Guidelines for National Greenhouse Gas Inventories. Where applicable, references have been made to earlier IPCC guidelines and guidance documents from 1996 and updated methodologies from the 2019 refinement. The methodologies used to estimate Tanzania's greenhouse gas inventories have improved over time and will continue to be refined as new data, methodologies, and international practices evolve. The impacts of refinements to methodologies and revisions of datasets are reported in a dedicated recalculations section for each sector.

The preparation of the NIR not only fulfils Tanzania's international reporting obligations but also offers significant benefits to national development and capacity building, particularly in the following ways: continuous capacity development among major stakeholders; provision of critical data to inform policy on GHG mitigation options; support for the evaluation of low-carbon development pathways; establishment of a foundation for setting national emission reduction targets; and feedback on progress toward achieving GHG reduction goals, including the volume of emissions reductions achieved, the sectors responsible, and the policies driving these reductions. The inventory includes key productive sectors that contribute to Tanzania’s economic development. Emission levels and removals across sectors are influenced by:

a.	Sector-specific mitigation policies,
b.	The deployment of environmentally sound technologies, and
c.	The degree of sustainability integrated into productivity.

Emissions and removals are classified under the four sectors defined by the 2006 IPCC guidelines: (1) Energy, (2) Industrial Processes and Product Use (IPPU), (3) Agriculture, Forestry, and Other Land Use (AFOLU) and (4) Waste. These sectors encompass the main economic activities that emit or remove greenhouse gases from the atmosphere. National emissions have been estimated by characterizing emissions/removal sources into the following hierarchical categories: (a) activities, (b) sub-categories, (c) categories, and (d) sectors. These classifications have been aggregated to provide economy-wide estimates of emissions and removals. Over the past three decades the greenhouse gas inventory of Tanzania has shown significant transformations across all sectors, the analysis of this inventory reveals both challenges and achievements across different economic sectors. 

These include the energy sector, Waste sector, Industrial Processes and Product Use (IPPU), and Agriculture, Forestry, and Other Land Use (AFOLU) sector which have shown a drastic transformation. Most notably, the AFOLU (Agriculture, Forestry, and Other Land Use) sector has transformed dramatically, with carbon sequestration capacity increasing by 135429 Gg CO2 equivalent (from a 188593 Gg CO2 in 1996 to a substantial carbon sink of 324,021.68 Gg CO2 in 2021). Within the same sector (AFOLU), methane emissions have increased by 3,269.69 Gg CO2 equivalent (from 2,359.87 to 5,629.56 Gg CO2 equivalent in 1990 to 2021). 

The energy sector shows a net increase of 4,725.95 Gg CO2 equivalent (from 85.72 to 4,811.68 Gg CO2 equivalent in 1990 to 2021). This can be attributed to Tanzania's economic development and urbanization. In the Industrial Processes and Product Use (IPPU) sector, HFC emissions have increased by 16,894.16 Gg CO2 equivalent (from -4,072.68 to 12,821.48 Gg CO2 equivalent). Meanwhile CO2 emissions have increase by 42164.07 Gg which shows a significant industrial growth and expansion within the country possibly due to government policy (Tanzania ya Viwanda). For the waste sector Methane emissions has increased by 37.38 Gg CO2 equivalent (from 1.63 to 39.01 Gg CO2 equivalent). This is attributed to increased population growth and significant urbanization. 

The combined effect of these sectoral changes has contributed to Tanzania's overall sequestration by at least 135089 Gg CO2 equivalent (from positive emissions of 71,039.30 Gg CO2 equivalent in 1990 to net absorption of -206,128.34 Gg CO2 equivalent in 2021), primarily due to increased carbon sequestration capacity in the AFOLU sector specifically in the LULUCF subsector. Methane emission has increased from 2361.495 in 1990 to 5668.567 in 2021, this is attributed to an increase in cattle population which have increased drastically during that period. Nitrous Oxide have also increased from 8.356541 Gg CO2 equivalent in 1990 to 28.31175 Gg CO2 equivalent in 2021. 

Being a net absorber of carbon dioxide uniquely positions the United Republic of Tanzania among developing nations, showing that development and economic growth that have occurred in the country coexist with environmental stewardship. The data suggests a critical need to maintain forest conservation efforts while managing the increasing emissions from energy, industrial, and waste sectors, particularly as the country continues with its developmental plans.  


# Technical contributors {.unumbered}

## Coordinators {.unumbered}
1.	Eng. Cyprian John Luhemeja (**Permanent Secretary, Vice President’s Office**)
2.	Dr. Freddy Manyika (Division of Environment, Vice President’s Office)
3.	Eng. Juma Limbe (Division of Environment, Vice President’s Office)
4.	Prof. Eliakimu Zahabu (Coordinator, National Carbon Monitoring Centre)
5.	Dr. Deo Shirima (Senior Safeguard Information System Officer, National Carbon Monitoring Centre)
6.	Dr. Paulo Lyimo (Biodiversity Conservationist, National Carbon Monitoring Centre)

## Energy Sector {.unumbered}
1.	Dr. Sara Osima (Tanzania Meteorological Authority)
2.	Dr. Neema Kitasho (Sokoine University of Agriculture)
3.	Dr. Esebi Nyari (Dar es Saalam Institute of Technology)
4.	Ms. Maryrose Batenga (Climate Action Network Tanzania)
5.	Ms. Elizabeth Philipo (Ministry of Energy)
6.	Mr. Jonathan Bruno (Ministry of Energy)

## Industrial Processes and Product Use (IPPU) {.unumbered}

1.	Dr. Christopher Warbug (Sokoine University of Agriculture)
2.	Mr. Maliki A. Maliki (Vice President’s Office)
3.	Ms. Sarafina Masanja (Sokoine University of Agriculture)
4.	Eng. Cyril Kimario (Tanzania Bureau of Standards)
5.	Dr. Zainabu Katima (University of Dar es Saalam)
6.	Mr. Hamdu Hamdani (Zanzibar Environmental Management Authority)
7.	Mr. Mathias Chanila (Tanzania Revenue Authority)

## AFOLU sector {.unumbered}

1.	Mr. Deogratius Gambago (Ministry of Fisheries and Livestock)
2.	Dr. Zabron Nziku (Tanzania Livestock Research Institute)
3.	Dr. Elikana John (Tanzania Forest Service Agency)
4.	Dr. Masumbuko Semba (Nelson Mandela African Institution of Science and Technology)
5.	Dr. Issa Nyashilu (Vice President’s Office)
6.	Mr. Fikiri Mhenga (Sokoine University of Agriculture)
7.	Mr. Abdallah Lungo (Vice President’s Office)
8.	Mr. Melkizedeck Dunda (Sokoine University of Agriculture)
9.	Mr. Kamwesige Mtendei (Ministry of Agriculture and Irrigation)
10.	Mrs. Miza Suleiman (Ministry of Agriculture, Irrigation, Natural Resource and Livestock)
11.	Mr. Abbas Mzee (Ministry of Agriculture, Irrigation, Natural Resource and Livestock)
12.	Mr. Japhet Safiel (Sokoine University of Agriculture)
13.	Mr. Frank Mathias (Sokoine University of Agriculture)

## Waste sector {.unumbered}

1.	Mr. Joseph Qamara (Climate Action Network Tanzania)
2.	Mr. Mohamed Suleiman (Central Town Council)
3.	Mr. Rogassian Lukoa (President’s Office, Regional Administration and Local Government)
4.	Ms. Diana Tesha (Sokoine University of Agriculture)
5.	Mr. Julius Enock (Vice President’s Office)


# Introduction {.unnumbered}

# ES 2 Summary of national GHG emission and removal estimates and trend {.unnumbered}

# Overview of source and sink estimates and trends by gas {.unnumbered}
